PlanetFinder/Pages/DataAnalysis/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanetFinder.AppCode.DataAnalysis;
using PlanetFinder.AppCode.DataStore;
using PlanetFinder.AppCode.DataStore.Tests;
using PlanetFinder.AppCode.Gateway;

namespace PlanetFinder.Pages.DataAnalysis
{
    public class IndexModel : PageModel
    {
        public string LogString { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPostAnalyzeData()
        {
            AzureDataStorer dataStorer = new AzureDataStorer();
            PlanetGroupAnalyzer dataAnalyzer = new PlanetGroupAnalyzer();
            
            DataAnalysisGateway gateway = new DataAnalysisGateway(dataStorer, dataAnalyzer);

            bool success;
            List<string> logEntries = gateway.AnalyzeAndStoreResults(true, out success);

            LogString = string.Join(Environment.NewLine, logEntries);

            return Page();
        }
    }
}

PlanetFinder/Pages/DataCollection/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanetFinder.AppCode.DataCollection;
using PlanetFinder.AppCode.DataStore;
using PlanetFinder.AppCode.Gateway;

namespace PlanetFinder.Pages.DataCollection
{
    public class IndexModel : PageModel
    {
        public string LogString { get; set; }
        public void OnGet()
        {
        }

        public IActionResult OnPostCollectData()
        {
            SwapiDataCollector dataCollector = new SwapiDataCollector();
            AzureDataStorer dataStorer = new AzureDataStorer();
            DataCollectionGateway gateway = new DataCollectionGateway(dataCollector, dataStorer);

            bool success;
            List<string> logEntries = gateway.CollectAndStore(true, out success);

            LogString = string.Join(Environment.NewLine, logEntries);

            return Page();
        }
    }
}

PlanetFinder/Pages/Echo/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PlanetFinder.Pages.Echo
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PlanetFinder/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace PlanetFinder.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

PlanetFinder/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PlanetFinder.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

PlanetFinder/Pages/PlanetGroups/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanetFinder.AppCode.DataAnalysis;
using PlanetFinder.AppCode.DataStore;

namespace PlanetFinder.Pages.PlanetGroups
{
    public class DetailsModel : PageModel
    {
        public DataStorePlanetGroup PlanetGroup { get; set; }

        public IList<DataStorePlanet> Planets { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AzureDataStorer dataStore = new AzureDataStorer();

            PlanetGroup = dataStore.GetPlanetGroup((int)id);

            Planets = dataStore.GetMatchingPlanets(PlanetGroup.Climate, PlanetGroup.Terrain)
                .OrderBy(planet => planet.Name)
                .ToList();

            return Page();
        }
    }
}

PlanetFinder/Pages/PlanetGroups/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanetFinder.AppCode.DataAnalysis;
using PlanetFinder.AppCode.DataObjects;
using PlanetFinder.AppCode.DataStore;

namespace PlanetFinder.Pages.PlanetGroups
{
    public class IndexModel : PageModel
    {
        public IList<DataStorePlanetGroup> PlanetGroups { get; set; }

        public void OnGet()
        {
            AzureDataStorer dataStorer = new AzureDataStorer();

            PlanetGroups = dataStorer.GetAllPlanetGroups()
                .OrderByDescending(group => group.PlanetCount)
                .ThenBy(group => group.Climate)
                .ThenBy(group => group.Terrain)
                .ToList();
        }
    }
}

PlanetFinder/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PlanetFinder.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

PlanetFinder/Pages/Tests/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanetFinder.AppCode.DataCollection;
using PlanetFinder.AppCode.DataCollection.Tests;
using PlanetFinder.AppCode.DataStore;
using PlanetFinder.AppCode.DataStore.Tests;
using PlanetFinder.AppCode.Gateway;
using PlanetFinder.AppCode.Gateway.Tests;

namespace PlanetFinder.Pages.Tests
{
    public class IndexModel : PageModel
    {
        public string TestResultsString { get; set; }
        public void OnGet()
        {
        }

        public IActionResult OnPostRunTests()
        {
            List<string> testResults = new List<string>();

            DataCollectionTests dataCollectionTests = new DataCollectionTests();

            testResults.Add("Running Data Collection Tests");

            dataCollectionTests.RunTests();

            testResults.Add("Data Collection Tests successful");

            DataStorerTests dataStorerTests = new DataStorerTests();

            testResults.Add("Running Data Store Tests");

            dataStorerTests.RunTests();

            testResults.Add("Data Store Tests successful");

            DataCollectionGatewayTests gatewayTests = new DataCollectionGatewayTests();

            testResults.Add("Running Data Collection Gateway Tests");

            gatewayTests.RunTests();

            testResults.Add("Data Collection Gateway Tests successful");

            TestResultsString = string.Join(Environment.NewLine, testResults);

            return Page();
        }
    }
}

PlanetFinder/Pages/DataAnalysis/Index.cshtml
@page
@model PlanetFinder.Pages.DataAnalysis.IndexModel
@{
    ViewData["Title"] = "Data Analysis";
}

<div class="text-center">
    <h1 class="display-4">Data Analysis</h1>
    <p>Please click on the button below to analyze the Planet Data to determine the climate / terrain pairings and store the results in an Azure database</p>
    <form id="form" name="form" method="post">
        <input name="btnAnalyze" id="btnAnalyze" asp-page-handler="AnalyzeData" type="submit" value="Analyze Data" class="btn btn-success" />
        <br />
        <br />
        <textarea asp-for="@Model.LogString" value="@Model.LogString" readonly="readonly" style="background-color: lightgray; width: 350px; height: 200px;"></textarea>
    </form>
</div>

PlanetFinder/Pages/DataCollection/Index.cshtml
@page
@model PlanetFinder.Pages.DataCollection.IndexModel
@{
    ViewData["Title"] = "Data Collection";
}

<div class="text-center">
    <h1 class="display-4">Data Collection</h1>
    <p>Please click on the button below to begin the data collection from <a href="https://swapi.tech/">https://swapi.tech/</a> (SW API) and store the data in a Microsoft Azure database</p>
    <form id="form" name="form" method="post">
        <input name="btnCollect" id="btnCollect" asp-page-handler="CollectData" type="submit" value="Collect Data" class="btn btn-success" />
        <br />
        <br />
        <textarea asp-for="@Model.LogString" value="@Model.LogString" readonly="readonly" style="background-color: lightgray; width: 350px; height: 200px;"></textarea>
    </form>
</div>

PlanetFinder/Pages/Echo/Index.cshtml
@page
@model PlanetFinder.Pages.Echo.IndexModel
@{
    ViewData["Title"] = "Echo";
}

<div class="text-center">
    <h1 class="display-4">Echo</h1>
    <p>Please enter the text you want to echo below</p>
    <input id="echoInput" name="echoInput" />
    <button id="button" name="button" onclick="copyText()">Echo Input</button> 
    <br />
    <br />
    <input id="echoOutput" name="echoOutput" readonly="readonly" style="background-color: lightgray;" />
</div>

<script type="text/javascript">
        function copyText() {
            var echoInput = $("#echoInput");
            var echoOutput = $("#echoOutput");

            if (echoInput && echoOutput) {
                echoOutput.val(echoInput.val());
            }
        }
</script>

PlanetFinder/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Coming soon...</p>
</div>

PlanetFinder/Pages/PlanetGroups/Details.cshtml
@page
@model PlanetFinder.Pages.PlanetGroups.DetailsModel
@{
    ViewData["Title"] = "Planet Group Details";
}

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlanetGroup.Climate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlanetGroup.Climate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlanetGroup.Terrain)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlanetGroup.Terrain)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlanetGroup.PlanetCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlanetGroup.PlanetCount)
        </dd>
    </dl>
</div>

<div class="card">
    <div class="card-header">
        Planets
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Planets[0].Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Planets[0].Climate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Planets[0].Gravity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Planets[0].Population)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Planets[0].SurfaceWater)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Planets[0].Terrain)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Planets)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Climate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gravity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Population)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SurfaceWater)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Terrain)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PlanetFinder/Pages/PlanetGroups/Index.cshtml
@page
@model PlanetFinder.Pages.PlanetGroups.IndexModel
@{
    ViewData["Title"] = "Planet Groups";
}

<div class="text-center">
    <h1 class="display-4">Star Wars Planet Groups</h1>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PlanetGroups[0].Climate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PlanetGroups[0].Terrain)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PlanetGroups[0].PlanetCount)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PlanetGroups)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Climate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Terrain)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PlanetCount)
                    </td>
                    <td>
                        <a asp-page="./Details" asp-route-id="@item.ID">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

PlanetFinder/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlanetFinder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlanetFinder.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PlanetFinder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Echo/Index">Echo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/DataCollection/Index">Data Collection</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/DataAnalysis/Index">Data Analysis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/PlanetGroups/Index">Planet Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Tests/Index">Run Tests</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PlanetFinder - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PlanetFinder/Pages/Tests/Index.cshtml
@page
@model PlanetFinder.Pages.Tests.IndexModel
@{
    ViewData["Title"] = "Run Tests";
}

<div class="text-center">
    <h1 class="display-4">Run Tests</h1>
    <p>Please click on the button below to run the project tests</p>
    <form id="form" name="form" method="post">
        <input name="btnRunTests" id="btnRunTests" asp-page-handler="RunTests" type="submit" value="Run Tests" class="btn btn-success" />
        <br />
        <br />
        <textarea asp-for="@Model.TestResultsString" value="@Model.TestResultsString" readonly="readonly" style="background-color: lightgray; width: 350px; height: 200px;"></textarea>
    </form>
</div>